####################################################################
# This script determines how to plot tagged regions on a map
#  Handles tagged regions for combined bk 0ka and aaf 2090CE time slice
#  Note that these are almost the same as the bk 0ka tags except
#  sundaland and sundaocean are combined
####################################################################

import matplotlib.lines as lines
import cartopy.crs as ccrs
import numpy as np

####################################################################
# Helpers
####################################################################

def _to_geo_lon(x):
    """Normalize longitude to [-180, 180]."""
    return (float(x) + 180.0) % 360.0 - 180.0

def _iter_segments(w, e, eps=1e-9):
    """
    Yield non-wrapping lon segments and flags showing if a seam edge was GENERATED by splitting.
    Returns (w_i, e_i, left_is_generated, right_is_generated).
    """
    W = _to_geo_lon(w)
    E = _to_geo_lon(e)
    if W <= E:
        yield (W, E, False, False)
    else:
        # Wrap -> split and mark seam edges as generated
        yield (W, 180.0, False, True)      # right edge at 180 is generated
        yield (-180.0, E, True, False)     # left edge at -180 is generated

def _add_hline_geo(ax, y, x0, x1, linestyle='-', color='k',
                   lw=0.8, zorder=10, transform=None):
    """Horizontal line from x0 to x1, splitting at dateline as needed (nudged off seam)."""
    if transform is None:
        transform = ccrs.PlateCarree()
    eps = 1e-9
    for w, e, _, _ in _iter_segments(x0, x1, eps=eps):
        if abs(e - 180.0) < 2*eps: e = 180.0 - eps
        if abs(w + 180.0) < 2*eps: w = -180.0 + eps
        ax.add_line(lines.Line2D([w, e], [y, y],
                                 linestyle=linestyle, color=color, lw=lw,
                                 zorder=zorder, transform=transform))

def _add_vline_geo(ax, x, y0, y1, linestyle='-', color='k',
                   lw=0.8, zorder=10, transform=None):
    """Vertical line at longitude x."""
    if transform is None:
        transform = ccrs.PlateCarree()
    y_min = float(min(y0, y1))
    y_max = float(max(y0, y1))
    xv = _to_geo_lon(x)
    ax.add_line(lines.Line2D([xv, xv], [y_min, y_max],
                             linestyle=linestyle, color=color, lw=lw,
                             zorder=zorder, transform=transform))

def _add_rect_geo(ax, rlats, rlatn, rlonw, rlone,
                  linestyle='-', edgecolor='r',
                  linewidth=0.8, zorder=10, transform=None,
                  suppress_seam_vertical=False):
    """
    Draw rectangle outline only (no fill).

    - Always draw top/bottom edges (split at dateline as needed).
    - Draw vertical edges normally, EXCEPT:
        * edges at ±180 CREATED BY wrap-splitting are omitted; and
        * if suppress_seam_vertical=True, ANY vertical exactly at ±180 is omitted
          (even if explicitly requested).
    """
    if transform is None:
        transform = ccrs.PlateCarree()
    lat0 = float(min(rlats, rlatn))
    lat1 = float(max(rlats, rlatn))
    if lat1 <= lat0:
        return

    eps = 1e-9
    def _on_seam(x): return abs(abs(x) - 180.0) < 2*eps

    for w, e, left_gen, right_gen in _iter_segments(rlonw, rlone, eps=eps):
        # horizontal edges
        _add_hline_geo(ax, y=lat0, x0=w, x1=e,
                       linestyle=linestyle, color=edgecolor, lw=linewidth,
                       zorder=zorder, transform=transform)
        _add_hline_geo(ax, y=lat1, x0=w, x1=e,
                       linestyle=linestyle, color=edgecolor, lw=linewidth,
                       zorder=zorder, transform=transform)

        # left vertical
        draw_left = True
        if left_gen and _on_seam(w):
            draw_left = False
        if suppress_seam_vertical and _on_seam(w):
            draw_left = False
        if draw_left:
            _add_vline_geo(ax, x=w, y0=lat0, y1=lat1,
                           linestyle=linestyle, color=edgecolor, lw=linewidth,
                           zorder=zorder, transform=transform)

        # right vertical
        draw_right = True
        if right_gen and _on_seam(e):
            draw_right = False
        if suppress_seam_vertical and _on_seam(e):
            draw_right = False
        if draw_right:
            _add_vline_geo(ax, x=e, y0=lat0, y1=lat1,
                           linestyle=linestyle, color=edgecolor, lw=linewidth,
                           zorder=zorder, transform=transform)

####################################################################
# Land tags
####################################################################

def draw_land_tags(numtag, ax, lw, major, minor, color, zorder):
    """
    Draw one land tag (numtag) onto ax.
    Land tags keep explicit 180° borders where defined.
    """
    # I'm not very happy with this solution to use two kwarg dicts but it's my best idea for now
    SL = dict(linestyle=major, color=color, lw=lw, zorder=zorder)
    SR = dict(linestyle=major, edgecolor=color, linewidth=lw, zorder=zorder)

    if numtag == 0:
        # 1. Antarctica (line across -60)
        _add_hline_geo(ax, y=-60, x0=-180, x1=180, **SL)

    if numtag == 1:
        # 2. North America
        _add_rect_geo(ax, rlats=15, rlatn=90, rlonw=-180, rlone=-18, **SR)

    if numtag == 2:
        # 3. South America (-Amazon)
        _add_rect_geo(ax, rlats=-60, rlatn=15, rlonw=-180, rlone=-18, **SR)

    if numtag == 3:
        # 4. Eurasia (polyline via axis-aligned segments)
        _add_hline_geo(ax, y=90, x0=-18, x1=180, **SL)        # north
        _add_vline_geo(ax, x=180, y0=4, y1=90, **SL)          # east
        _add_hline_geo(ax, y=4,  x0=119, x1=180, **SL)
        _add_vline_geo(ax, x=119, y0=4,  y1=17,  **SL)
        _add_hline_geo(ax, y=17, x0=95,  x1=119, **SL)
        _add_vline_geo(ax, x=95,  y0=4,  y1=17,  **SL)
        _add_hline_geo(ax, y=4,  x0=52,  x1=95,  **SL)
        _add_vline_geo(ax, x=52,  y0=4,  y1=37,  **SL)
        _add_hline_geo(ax, y=37, x0=-18, x1=52,  **SL)
        _add_vline_geo(ax, x=-18, y0=37, y1=90,  **SL)        # west

    if numtag == 4:
        # 5. Africa (-Congo)
        _add_rect_geo(ax, rlats=-60, rlatn=37, rlonw=-18, rlone=52, **SR)

    if numtag == 5:
        # 10. Sundaland combined
        _add_rect_geo(ax, rlats=-10, rlatn=17, rlonw=95, rlone=119, **SR)

    if numtag == 6:
        # 10. Sahulland
        _add_rect_geo(ax, rlats=-19, rlatn=4, rlonw=119, rlone=150, **SR)

    if numtag == 7:
        # 11. Australia/Oceania (explicitly ends at 180 -> keep that border)
        _add_rect_geo(ax, rlats=-60, rlatn=4, rlonw=52, rlone=180, **SR)

    if numtag == 8:
        # 12. Amazon
        _add_rect_geo(ax, rlats=-10, rlatn=10, rlonw=-70, rlone=-45,
                      linestyle=minor, edgecolor=color, linewidth=lw, zorder=zorder)

    if numtag == 9:
        # 13. Congo
        _add_rect_geo(ax, rlats=-10, rlatn=10, rlonw=10, rlone=35,
                      linestyle=minor, edgecolor=color, linewidth=lw, zorder=zorder)

####################################################################
# Ocean tags
####################################################################

def draw_ocean_tags(numtag, ax, lw, major, minor, color, zorder):
    """
    Draw one ocean tag (numtag) onto ax.
    Ocean rectangles suppress any vertical seam drawn at ±180.
    """
    SL = dict(linestyle=major, color=color, lw=lw, zorder=zorder)
    SR = dict(linestyle=major, edgecolor=color, linewidth=lw, zorder=zorder)

    if numtag == 10:
        # 14. North Pacific (two spans)
        _add_rect_geo(ax, rlats=25, rlatn=90, rlonw=-180, rlone=-100,
                      suppress_seam_vertical=True, **SR)
        _add_rect_geo(ax, rlats=25, rlatn=90, rlonw=118,  rlone=180,
                      suppress_seam_vertical=True, **SR)

    if numtag == 11:
        # 15. North Atlantic (polyline)
        _add_vline_geo(ax, x=0,   y0=25, y1=48, **SL)
        _add_hline_geo(ax, y=48,  x0=0,  x1=20, **SL)
        _add_vline_geo(ax, x=20,  y0=48, y1=90, **SL)
        _add_hline_geo(ax, y=90,  x0=-100, x1=20, **SL)
        _add_vline_geo(ax, x=-100, y0=48, y1=90, **SL)
        _add_hline_geo(ax, y=48,  x0=-100, x1=-75, **SL)
        _add_vline_geo(ax, x=-75, y0=25, y1=48, **SL)
        _add_hline_geo(ax, y=25,  x0=-75, x1=0, **SL)

    if numtag == 12:
        # 16. North Barents/Arctic Sea
        _add_rect_geo(ax, rlats=48, rlatn=90, rlonw=20, rlone=118,
                      suppress_seam_vertical=True, **SR)

    if numtag == 13:
        # 17. Tropical Pacific NE (polyline)
        _add_hline_geo(ax, y=25,  x0=-150, x1=-100, **SL)
        _add_vline_geo(ax, x=-100, y0=18,  y1=25,  **SL)
        _add_hline_geo(ax, y=18,  x0=-100, x1=-92, **SL)
        _add_vline_geo(ax, x=-92, y0=15,  y1=18,  **SL)
        _add_hline_geo(ax, y=15,  x0=-92, x1=-84, **SL)
        _add_vline_geo(ax, x=-84, y0=8,   y1=15,  **SL)
        _add_hline_geo(ax, y=8,   x0=-84, x1=-75, **SL)
        _add_vline_geo(ax, x=-75, y0=0,   y1=8,   **SL)
        _add_hline_geo(ax, y=0,   x0=-150, x1=-75, **SL)
        _add_vline_geo(ax, x=-150, y0=0,  y1=25,  **SL)

    if numtag == 14:
        # 18. Caribbean (polyline)
        _add_hline_geo(ax, y=48,  x0=-100, x1=-75, **SL)
        _add_vline_geo(ax, x=-75, y0=18,  y1=48,  **SL)
        _add_vline_geo(ax, x=-100, y0=18, y1=48,  **SL)
        _add_hline_geo(ax, y=18,  x0=-100, x1=-92, **SL)
        _add_vline_geo(ax, x=-92, y0=15,  y1=18,  **SL)
        _add_hline_geo(ax, y=15,  x0=-92, x1=-84, **SL)
        _add_vline_geo(ax, x=-84, y0=8,   y1=15,  **SL)
        _add_hline_geo(ax, y=8,   x0=-84, x1=-75, **SL)

    if numtag == 15:
        # 19. Tropical Atlantic NW
        _add_rect_geo(ax, rlats=0, rlatn=25, rlonw=-75, rlone=-30,
                      suppress_seam_vertical=True, **SR)

    if numtag == 16:
        # 20. Tropical Atlantic NE
        _add_rect_geo(ax, rlats=0, rlatn=25, rlonw=-30, rlone=20,
                      suppress_seam_vertical=True, **SR)

    if numtag == 17:
        # 21. Mediterranean
        _add_rect_geo(ax, rlats=30, rlatn=48, rlonw=0, rlone=45,
                      suppress_seam_vertical=True, **SR)

    if numtag == 18:
        # 22. Indian Ocean NW/Arabian Sea
        _add_rect_geo(ax, rlats=4, rlatn=30, rlonw=30, rlone=75,
                      suppress_seam_vertical=True, **SR)

    if numtag == 19:
        # 23. Indian Ocean NE/Bay of Bengal
        _add_rect_geo(ax, rlats=4, rlatn=30, rlonw=75, rlone=95,
                      suppress_seam_vertical=True, **SR)

    if numtag == 20:
        # 26. Sundaland combined
        _add_rect_geo(ax, rlats=-10, rlatn=17, rlonw=95, rlone=119,
                      suppress_seam_vertical=True, **SR)

    if numtag == 21:
        # 27. Tropical Pacific NW
        _add_rect_geo(ax, rlats=4, rlatn=25, rlonw=95, rlone=150,
                      suppress_seam_vertical=True, **SR)

    if numtag == 22:
        # 29. Tropical Pacific North Central (two spans)
        _add_rect_geo(ax, rlats=0,  rlatn=25, rlonw=-180, rlone=-150,
                      suppress_seam_vertical=True, **SR)
        _add_rect_geo(ax, rlats=0,  rlatn=25, rlonw=150,  rlone=180,
                      suppress_seam_vertical=True, **SR)

    if numtag == 23:
        # 30. Tropical Pacific SE
        _add_rect_geo(ax, rlats=-25, rlatn=0, rlonw=-150, rlone=-60,
                      suppress_seam_vertical=True, **SR)

    if numtag == 24:
        # 31. Tropical Atlantic SW
        _add_rect_geo(ax, rlats=-25, rlatn=0, rlonw=-60, rlone=-10,
                      suppress_seam_vertical=True, **SR)

    if numtag == 25:
        # 32. Tropical Atlantic SE
        _add_rect_geo(ax, rlats=-25, rlatn=0, rlonw=-10, rlone=20,
                      suppress_seam_vertical=True, **SR)

    if numtag == 26:
        # 33. Tropical Indian Ocean SW
        _add_rect_geo(ax, rlats=-25, rlatn=4, rlonw=30, rlone=70,
                      suppress_seam_vertical=True, **SR)

    if numtag == 27:
        # 34. Tropical Indian Ocean South Central
        _add_rect_geo(ax, rlats=-25, rlatn=4, rlonw=70, rlone=95,
                      suppress_seam_vertical=True, **SR)

    if numtag == 28:
        # 35. Tropical Indian Ocean SE
        _add_rect_geo(ax, rlats=-25, rlatn=-10, rlonw=95, rlone=119,
                      suppress_seam_vertical=True, **SR)

    if numtag == 29:
        # 36. Sahul region ocean
        _add_rect_geo(ax, rlats=-25, rlatn=4, rlonw=119, rlone=150,
                      suppress_seam_vertical=True, **SR)

    if numtag == 30:
        # 37. Tropical Pacific South Central (two spans)
        _add_rect_geo(ax, rlats=-25, rlatn=0, rlonw=-180, rlone=-150,
                      suppress_seam_vertical=True, **SR)
        _add_rect_geo(ax, rlats=-25, rlatn=0, rlonw=150,  rlone=180,
                      suppress_seam_vertical=True, **SR)

    if numtag == 31:
        # 38. South Pacific (two spans)
        _add_rect_geo(ax, rlats=-90, rlatn=-25, rlonw=-180, rlone=-70,
                      suppress_seam_vertical=True, **SR)
        _add_rect_geo(ax, rlats=-90, rlatn=-25, rlonw=140,  rlone=180,
                      suppress_seam_vertical=True, **SR)

    if numtag == 32:
        # 39. South Atlantic
        _add_rect_geo(ax, rlats=-90, rlatn=-25, rlonw=-70, rlone=25,
                      suppress_seam_vertical=True, **SR)

    if numtag == 33:
        # 40. South Indian Ocean
        _add_rect_geo(ax, rlats=-90, rlatn=-25, rlonw=25, rlone=140,
                      suppress_seam_vertical=True, **SR)
